### ISSUE TITLE
As a Student, I want to delete my Submission

### ISSUE THREAD

**Issue by PopBogdan97** [Fodark/shfuggiente_se2#24]
DELETE - /submissions/id

How to Demo:
Send a DELETE request to `/submissions/5` where `5` is the ID of a submission

If successfully the response will have status `200` with body like:
```
{
  status: "successful"
}
```

Then a GET request to `/submissions/5` will have a status `404`

**Comment by PopBogdan97** [comment]
https://shfuggientese2.docs.apiary.io/#reference/submissions/apiv1submissionsid/delete-the-submission

**Comment by GianDigia** [comment]
Done in 167786c231239cd7feefdedcbaa32e51d4afd1fb
