### ISSUE TITLE
As a Student, I want to get information of my submission

### ISSUE THREAD

**Issue by PopBogdan97** [Fodark/shfuggiente_se2#25]
GET - /submissions/id

How to Demo:
Send a GET to `/submissions/3` when `3` is the id of a submission and expect a response like:
```
{
  userId: 3,
  examId: 54,
  answers: [ {32: "New answer 1" }, {56: "New answer 2" }, {102: "New answer 3" } ]
}
```

**Comment by PopBogdan97** [comment]
https://shfuggientese2.docs.apiary.io/#reference/submissions/apiv1submissionsid/get-info-about-submission

**Comment by GianDigia** [comment]
0122afe15a6186f5e50cb61b43071f8a9ccde125
