### ISSUE TITLE
As an User, I want to get all the Users

### ISSUE THREAD

**Issue by PopBogdan97** [Fodark/shfuggiente_se2#34]
GET - /users

How to Demo:
Send a GET request to `/users` and expect a response like:
```
[
  {
    "id": 1,
    "name": "Gianmarco"
  },
  {
    "id": 2,
    "name": "Andrea"
  },
  ...
]
```

**Comment by Fodark** [comment]
https://shfuggientese2.docs.apiary.io/reference/users/apiv1users/get-a-list-of-the-users
