### ISSUE TITLE
As a Student, I want to get the all my Submissions

### ISSUE THREAD

**Issue by PopBogdan97** [Fodark/shfuggiente_se2#35]
GET - /users/:id/submissions

Send a GET request to `/users/3/submissions` where `3` is your ID
Expext a response like:
```
{
  "submissions_ids": [
    1,
    54,
    76,
    43,
    87
  ]
}
```

**Comment by Fodark** [comment]
https://shfuggientese2.docs.apiary.io/#reference/users/apiv1usersidsubmissions/get-the-submissions'-ids-related-to-a-user
